name: Docker Image CI

on: 
  push:
    branches: 
      - master
  
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Python Code
        run: python3 -m compileall -f -l .
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
