name: Docker Image Publish

on: 
  push:
    branches:
      - master
      - dev
      
env:
  IMAGE_NAME: env_sensor_data_processor

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - uses: luizfzs/env-sensor-data-processor/.github/workflows/validate_code_and_build_docker_image
      
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        
      - name: Publish Image to Registry
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          VERSION=20191204012926
          # VERSION=$(date +%Y%m%d%H%M%S)
          
          echo IMAGE_NAME:$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}
          docker push ${IMAGE_ID}:${VERSION}
